CREATE TABLE DEPTO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(50));

ALTER TABLE DEPTO
ADD CONSTRAINT PK_DEPTO
PRIMARY KEY (ID);

CREATE TABLE FUNCIONARIO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100),
    CPF VARCHAR(18),
    ENDERECO VARCHAR(100),
    BAIRRO VARCHAR(50),
    IDCIDADE INTEGER,
    IDDEPTO INTEGER,
    SALARIO DECIMAL(15,2));

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO
PRIMARY KEY (ID);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_1
FOREIGN KEY (IDDEPTO)
REFERENCES DEPTO(ID);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_2
FOREIGN KEY (IDCIDADE)
REFERENCES CIDADE(ID);

RECONNECT;

INSERT INTO DEPTO (ID, NOME)
           VALUES (1, 'FINANCEIRO');
INSERT INTO DEPTO (ID, NOME)
           VALUES (2, 'VENDAS');
INSERT INTO DEPTO (ID, NOME)
           VALUES (3, 'COMPRAS');

COMMIT WORK;


